Fix 2 codemagic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -11,10 +11,15 @@ workflows:
         bundle_identifier: com.mek.calaifit
       vars:
         BUNDLE_ID: "com.mek.calaifit"
-        XCODE_PROJECT: "CalAI.xcworkspace" # Используем .xcworkspace вместо .xcodeproj
+        XCODE_PROJECT: "CalAI.xcworkspace"
         XCODE_SCHEME: "CalAI"
         APP_STORE_APPLE_ID: 6743544003
-      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
+      xcode: latest
+      cache:
+        paths:
+          - ~/.cocoapods/repos  # Кешируем CocoaPods
+          - ~/Library/Developer/Xcode/DerivedData  # Кеш Xcode
+          - ~/Library/Caches/com.apple.dt.Xcode  # Кеш SPM-зависимостей
     scripts:
       - name: Install CocoaPods dependencies
         script: |
@@ -30,8 +35,13 @@ workflows:
       - name: Increment build number
         script: |
           cd $CM_BUILD_DIR
-          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
-          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
+          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || echo 0)
+          if [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
+            agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
+          else
+            echo "Warning: Could not retrieve latest build number, using default."
+            agvtool new-version -all 1
+          fi
       - name: Build ipa for distribution
         script: |
           xcode-project build-ipa \
@@ -51,14 +61,8 @@ workflows:
           failure: false
       app_store_connect:
         auth: integration
-
-        # Configuration related to TestFlight (optional)
-        # Note: This action is performed during post-processing.
         submit_to_testflight: true
-        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
+        beta_groups:
           - group name 1
           - group name 2
-
-        # Configuration related to App Store (optional)
-        # Note: This action is performed during post-processing.
         submit_to_app_store: false
